# Generated by Django 4.2.1 on 2024-05-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('deadline', models.DateTimeField(blank=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('medium', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
