# Generated by Django 4.2.1 on 2024-05-04 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_emailsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
