# Generated by Django 4.2.1 on 2024-05-06 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0003_jobapplication_posted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('job_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
