# Generated by Django 4.2.1 on 2024-05-06 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_userjobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobapplication',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userjobapplication',
            name='application_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
